### PR TITLE
Adding Gaspard's page and publications

### PR DESCRIPTION
**Pull request by gfarge**
Added my author page, manually changed the author name "Gaspard Farge" to "gfarge" in farge-2020 so that it can be linked to my author profile (hopefully?), manually added "farge-2021" to feature my new publication! Hope that's ok, don't hesitate to remove it if it's not its place.

### CODE REVIEW

**Review by beridel — COMMENTED** [review]
I'm not quite sure what's best for adding everyone's publications... My initial thought was to just include publications done here (so for example your recent one with Claude and Nikloai wouldn't fit), but what do you think?

**Comment by gfarge** [comment]
Perhaps it's going to be a bit too messy if everyone adds theirs, even if unrelated to the group, that's true! 

Although I think it's important that the viewer can access a full list of publications, if they find the page looking for a specific member of the group, it is better publicity :^)

In my case, I can just link to the ipgp profile, it could be the best way to keep it simple?

**Comment by beridel** [comment]
I think linking elsewhere for now and keeping it simple sounds good. Do you mind removing then that extra pub from the pull request?

**Comment by gfarge** [comment]
Ok, I removed the extra publication and added the link to the bio! Let me know if it's good to be merged now.

**Pull request merged**
